const puppeteer = require('puppeteer-core');
const logger = require('../logger'); 

async function automateRadiusToken(userId) {
    let browser;
    try {
        logger.info(`Starting UI Automation Engine for User Data: ${userId}`);
        
        browser = await puppeteer.launch({ 
            headless: false, // প্রোডাকশনে যাওয়ার সময় এটা true করে দেবেন
            executablePath: 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe', 
            userDataDir: './data/browser_session', 
            args: ['--no-sandbox', '--disable-setuid-sandbox', '--start-maximized'] 
        });

        const page = await browser.newPage();
        await page.setDefaultTimeout(120000);

        // ==========================================
        // 🔐 ধাপ ১: স্মার্ট লগইন লজিক
        // ==========================================
        await page.goto('https://billing.circlenetworkbd.net/admin/login', { waitUntil: 'networkidle2' });

        if (page.url().includes('login')) {
            logger.info("Executing fresh login...");
            if (await page.$('#form2Example11')) {
                await page.click('#form2Example11', { clickCount: 3 });
                await page.keyboard.press('Backspace');
                await page.type('#form2Example11', process.env.RADIUS_USER);
            }
            if (await page.$('#form2Example22')) {
                await page.click('#form2Example22', { clickCount: 3 });
                await page.keyboard.press('Backspace');
                await page.type('#form2Example22', process.env.RADIUS_PASS);
            }
            if (await page.$('#logInBtn')) {
                await page.click('#logInBtn');
                await page.waitForNavigation({ waitUntil: 'networkidle2' }).catch(() => {});
            }
        } else {
            logger.info("Session active. Skipping login screen.");
        }

        // ==========================================
        // 🔍 ধাপ ২: Client Search পেজ (Smart Identification)
        // ==========================================
        await page.goto('https://billing.circlenetworkbd.net/admin/clientSearch', { waitUntil: 'networkidle2' });

        logger.info(`Smart Searching for: ${userId}`);

        // স্মার্ট চেকিং: ফোন নাম্বার (+880/01), CID নাকি Username?
        const isPhoneNumber = /^(?:\+?88)?(01\d{9})$/.test(userId); 
        const isNumeric = /^\d+$/.test(userId) && !isPhoneNumber;

        if (isPhoneNumber) {
            const cleanPhone = userId.match(/(?:^\+?88)?(01\d{9})$/)[1]; 
            await page.type('input[placeholder="01234567891"]', cleanPhone); 
        } else if (isNumeric) {
            await page.type('input[placeholder="CID"]', userId); 
        } else {
            await page.type('input[placeholder="Username"]', userId); 
        }

        // Search বাটনে ক্লিক
        await page.evaluate(() => {
            const btns = Array.from(document.querySelectorAll('button'));
            const searchBtn = btns.find(b => b.innerText.includes('Search'));
            if (searchBtn) searchBtn.click();
        });
        
        await new Promise(r => setTimeout(r, 4000)); 

        // 🎯 টেবিল থেকে data-userid অ্যাট্রিবিউট স্ক্র্যাপ করা (সবচেয়ে নিখুঁত উপায়)
        const actualUsername = await page.evaluate(() => {
            const firstRow = document.querySelector('table tbody tr:first-child');
            return firstRow ? firstRow.getAttribute('data-userid') : null;
        });

        if (!actualUsername) {
            logger.warn(`User data "${userId}" not found. Aborting.`);
            await browser.close();
            return null; 
        }

        logger.info(`Match Found! Exact Username: ${actualUsername}. Proceeding...`);

        // ==========================================
        // 🎫 ও 📋 ধাপ ৩ ও ৪: টোকেন ক্রিয়েট এবং লিস্ট (একই পেজে)
        // ==========================================
        await page.goto('https://billing.circlenetworkbd.net/admin/add-token', { waitUntil: 'networkidle2' });
        
        const SEARCH_SELECTOR = 'input[placeholder="Search by customer user name"]';
        await page.waitForSelector(SEARCH_SELECTOR, { timeout: 10000 });
        await page.type(SEARCH_SELECTOR, actualUsername); 
        await page.keyboard.press('Enter');
        await new Promise(r => setTimeout(r, 3000)); 

        // 🔘 ড্রপডাউন সিলেকশন (⚠️ আপনার কাজ: ইনস্পেক্ট করে সঠিক ID বা name বসান)
        await page.select('#CHANGE_THIS_ID_TOKEN_CODE', 'Need Support'); 
        await page.select('#CHANGE_THIS_ID_CATEGORY', 'Problem');
        await page.select('#CHANGE_THIS_ID_SOURCE', 'Mail');
        
        await page.type('#CHANGE_THIS_ID_DESCRIPTION', "Generated by Bot via Email Request.");
        
        // 💾 সেভ বাটনে ক্লিক এবং পেজ রিলোড/আপডেটের জন্য অপেক্ষা
        await Promise.all([
            page.click('#CHANGE_THIS_ID_SAVE_BTN'),
            // সেভ করার পর পেজ রিলোড হলে বট অপেক্ষা করবে, না হলে স্কিপ করবে
            page.waitForNavigation({ waitUntil: 'networkidle2' }).catch(() => {}) 
        ]);
        await new Promise(r => setTimeout(r, 4000)); // ডাটা সেভ হয়ে লিস্টে আসার সেফটি বাফার

        // 🔍 লিস্ট ফিল্টারিং ও আইডি স্ক্র্যাপ (একই পেজে)
        await page.select('#CHANGE_THIS_ID_RESELLER', 'All');
        await page.select('#CHANGE_THIS_ID_TYPE', 'Logical');
        
        const listSearchBox = '#CHANGE_THIS_ID_SEARCH';
        await page.waitForSelector(listSearchBox);
        await page.click(listSearchBox, { clickCount: 3 });
        await page.keyboard.press('Backspace');
        await page.type(listSearchBox, actualUsername); 
        await page.keyboard.press('Enter');
        await new Promise(r => setTimeout(r, 4000)); // ফিল্টার রেজাল্ট আসার বাফার

        // 🎯 টেবিল থেকে নতুন তৈরি হওয়া টোকেন আইডি স্ক্র্যাপ
        const finalTokenId = await page.evaluate(() => {
            const firstRowId = document.querySelector('table tbody tr:first-child td:first-child');
            return firstRowId ? firstRowId.innerText.trim() : null;
        });
        
        logger.info(`Successfully retrieved Token ID: ${finalTokenId}`);
        await browser.close();
        return finalTokenId;

    } catch (error) {
        logger.error(`[Puppeteer Error]: ${error.message}`);
        if (browser) await browser.close();
        return null;
    }
}

module.exports = { automateRadiusToken };