const puppeteer = require('puppeteer');
const logger = require('../logger'); // আপনার Pino Logger

async function automateRadiusToken(userId) {
    let browser;
    try {
        logger.info(`Starting Radius Automation Engine for User ID: ${userId}`);
        
        browser = await puppeteer.launch({ 
            headless: true, // স্ক্রিন ব্যাকগ্রাউন্ডে লুকাতে true, লাইভ দেখতে চাইলে false করতে পারেন
            userDataDir: './data/browser_session', 
            args: ['--no-sandbox', '--disable-setuid-sandbox', '--start-maximized'] 
        });

        const page = await browser.newPage();
        await page.setDefaultTimeout(120000); // গ্লোবাল টাইমআউট ২ মিনিট
        await page.setDefaultNavigationTimeout(120000);

        // ==========================================
        // 🔐 ধাপ ১: অটো-লগইন প্রোটেকশন
        // ==========================================
        await page.goto('https://radius.ispname.com/login-page'); // 👈 আসল লগইন URL

        const LOGIN_BOX_SELECTOR = '#username'; 
        const isLoginRequired = await page.$(LOGIN_BOX_SELECTOR).then(el => el !== null).catch(() => false);

        if (isLoginRequired) {
            logger.info("Radius Session not found. Executing background auto-login...");
            await page.type('#username', 'YOUR_RADIUS_USERNAME'); // 👈 আপনার আসল রেডিয়াস আইডি
            await page.type('#password', 'YOUR_RADIUS_PASSWORD'); // 👈 আপনার আসল পাসওয়ার্ড
            await page.click('#login_btn_id'); // 👈 লগইন বাটনের আইডি
            await page.waitForNavigation({ waitUntil: 'networkidle2' });
            logger.info("Login process completed successfully.");
        } else {
            logger.info("Active session detected. Skipping login step.");
        }

        // ==========================================
        // 🎫 ধাপ ২: টোকেন ক্রিয়েট পেজ (অটো-ফিল এবং অটো-অ্যাসাইন)
        // ==========================================
        await page.goto('https://radius.ispname.com/token-page'); // 👈 আসল টোকেন ক্রিয়েট URL

        const SEARCH_SELECTOR = 'input[placeholder="Search by customer user name"]';
        await page.waitForSelector(SEARCH_SELECTOR, { timeout: 5000 });
        await page.type(SEARCH_SELECTOR, userId);
        await page.keyboard.press('Enter');

        await new Promise(r => setTimeout(r, 2000)); // CID, Name, Phone, Email অটো-ফিল হওয়ার বাফার

        // কাস্টমার আইডি ভ্যালিডেশন চেক (CID বক্স পূরণ হয়েছে কিনা)
        const isUserValid = await page.evaluate(() => {
            const cidInput = document.querySelector('input[placeholder="CID"]');
            return cidInput && cidInput.value.trim() !== '';
        });

        if (!isUserValid) {
            logger.warn(`User "${userId}" not found in Radius. Action Aborted.`);
            await page.close();
            return null; 
        }

        // 🔘 বক্স ১: Token Code ড্রপডাউন থেকে 'Need Support' সিলেক্ট
        const TOKEN_CODE_SELECTOR = '#CHANGE_THIS_TO_YOUR_DROPDOWN_ID'; 
        await page.waitForSelector(TOKEN_CODE_SELECTOR, { timeout: 3000 });
        await page.select(TOKEN_CODE_SELECTOR, 'Need Support'); 

        // 🔘 বক্স ২: Token Category ড্রপডাউন থেকে 'Problem' সিলেক্ট
        const TOKEN_CATEGORY_SELECTOR = '#CHANGE_THIS_TO_TOKEN_CATEGORY_DROPDOWN_ID'; 
        await page.select(TOKEN_CATEGORY_SELECTOR, 'Problem'); 

        // 🔘 বক্স ৩: Token Source ড্রপডাউন থেকে 'Mail' সিলেক্ট 
        const TOKEN_SOURCE_SELECTOR = '#CHANGE_THIS_TO_TOKEN_SOURCE_DROPDOWN_ID'; 
        await page.select(TOKEN_SOURCE_SELECTOR, 'Mail'); 

        // 🔘 বক্স ৪: Description বক্সে ফিক্সড টেক্সট টাইপ করা
        const DESCRIPTION_BOX = '#CHANGE_THIS_TO_DESCRIPTION_BOX_ID'; 
        const defaultDescription = "This ticket was automatically generated by the ISP Support Bot via email request. Please inspect the client line.";
        await page.type(DESCRIPTION_BOX, defaultDescription);

        // সেভ বাটন ক্লিক
        const SAVE_BUTTON_SELECTOR = '#CHANGE_THIS_TO_YOUR_SAVE_BUTTON_ID'; 
        await page.click(SAVE_BUTTON_SELECTOR);
        await new Promise(r => setTimeout(r, 2000)); // ডাটাবেজে সেভ হওয়ার সেফটি বাফার

        // ==========================================
        // 🔍 📋 ধাপ ৩: টোকেন লিস্ট পেজ ফিল্টারিং ও উপরের আইডি স্ক্র্যাপ
        // ==========================================
        await page.goto('https://radius.ispname.com/token-list-or-search-page'); // 👈 লিস্ট পেজের URL

        // 🔘 বক্স ৫: রিসেলার থেকে 'All' সিলেক্ট করা হলো
        const RESELLER_DROPDOWN = '#CHANGE_THIS_TO_RESELLER_DROPDOWN_ID';
        await page.waitForSelector(RESELLER_DROPDOWN, { timeout: 5000 });
        await page.select(RESELLER_DROPDOWN, 'All'); 

        // 🔘 বক্স ৬: টোকেন টাইপ থেকে 'Logical' সিলেক্ট করা
        const TOKEN_TYPE_DROPDOWN = '#CHANGE_THIS_TO_TOKEN_TYPE_DROPDOWN_ID';
        await page.select(TOKEN_TYPE_DROPDOWN, 'Logical'); 

        // ⏳ ডাইনামিক বাফারিং হ্যান্ডেলার (১০ সেকেন্ড লাগুক বা ১ মিনিট—ভ্যানিশ হওয়া মাত্র বট রেডি হবে)
        const BUFFERING_SELECTOR = '.loader'; // 👈 বাফারিং ওভারলে বা স্পিনারের আসল ক্লাস/আইডি
        logger.info("Search filters applied. Waiting for buffering overlay...");
        await page.waitForSelector(BUFFERING_SELECTOR, { visible: true, timeout: 15000 }).catch(() => {});
        await page.waitForSelector(BUFFERING_SELECTOR, { hidden: true, timeout: 120000 });

        // 🔘 বক্স ৭: নাম লেখার বক্সে 'Ahnaf Sadik Saad' লিখে ফিল্টার করা
        const LIST_SEARCH_BOX = '#CHANGE_THIS_TO_LIST_SEARCH_BOX_ID'; 
        await page.waitForSelector(LIST_SEARCH_BOX, { visible: true, timeout: 10000 });
        await page.type(LIST_SEARCH_BOX, 'Ahnaf Sadik Saad');
        await page.keyboard.press('Enter');

        await new Promise(r => setTimeout(r, 3000)); // টেবিল ফিল্টারিং শেষ হওয়ার ফাইনাল বাফার

        // 🎯 [Top Token Selector]: টেবিলের একদম প্রথম সারির (Latest Row) প্রথম কলাম থেকে আইডি স্ক্র্যাপ করা
        const LATEST_TOKEN_SELECTOR = 'table tbody tr:first-child td:first-child'; 
        await page.waitForSelector(LATEST_TOKEN_SELECTOR, { timeout: 5000 });
        
        const finalTokenId = await page.evaluate((sel) => {
            return document.querySelector(sel).innerText.trim();
        }, LATEST_TOKEN_SELECTOR);

        logger.info(`Successfully retrieved generated Top Token ID: ${finalTokenId}`);

        await browser.close();
        return finalTokenId;

    } catch (error) {
        logger.error(`[Puppeteer Automation Error]: ${error.message}`);
        if (browser) await browser.close();
        return null;
    }
}

module.exports = { automateRadiusToken };